### ISSUE TITLE
The Chicago Tribune's favicon is very small, and looks pixelated/distorted, in the `Customize Brave News` dialog.

### ISSUE THREAD

**Issue by stephendonner** [brave/news-aggregator#168] opened 2022-11-02 17:58 UTC
The Chicago Tribune's favicon is very small, and looks pixelated/distorted, in the `Customize Brave News` dialog.

STR:
1. install latest `beta` or `nightly`
2. enable `Brave News v2` flag in `brave://flags`
3. click `Relaunch`
4. open the Brave News `Customize` dialog
5. look for the Chicago Tribune favicon

<img width="1312" alt="Bildschirmfoto 2022-11-02 um 10 36 48 AM" src="https://user-images.githubusercontent.com/387249/199565653-c1e6a85b-2645-479a-973a-1ab61810a350.png">

**Comment by fallaciousreasoning** [comment] 2022-11-08 19:44
Looks like the Chicago Tribune doesn't specify any large icons, so we're going to need to have a system for manually overriding these

**Comment by aurangzaib048** [comment] 2022-11-08 19:52
for details: https://bravesoftware.slack.com/archives/CU56GUJ1H/p1667935931969549

**Comment by LorenzoMinto** [comment] 2023-12-04 16:44
Duplicate of https://github.com/brave/news-aggregator/issues/568

**Closed by LorenzoMinto** 2023-12-04 16:44 UTC
